@startuml Diagrama de clases
skinparam classAttributeIconSize 0
skinparam style strictuml
hide class circle
hide abstract circle


Class Juego{
  +nuevoJuego(cantidadDeJugadores)
  +atacarAPaís(in paísAtacante:País, in paísDefensor:País)
  +verificarQueDosPaísesSonLimítrofes(in País, in País): Boolean
  +verificarQueDosPaísesNoPertenecenAMismoJugador(in País, in País): Boolean
}
' Class Tablero{

' }
Class Tarjeta{
    -Pais
    -Simbolo
    ' +tieneMismoSimboloQue(DosTarjetas): Boolean
    +tieneMismoSimboloQue(UnaTarjeta): Boolean
}
Class Continente{
    +estaCompleto(): Boolean
}
Class Dado{
    +arrojar(unaCantidad)
}
Class Jugador{
    +nuevoJugador(Color)
    +ocupar(País)
    +verificarAtaqueValido(País)
    +desocupar(País)
}
Class País{
    +asignarDuenio(Jugador)
    +atacar(País)
    +esLimitrofe(País)
    +serAtacadoPor(Ejercito)
    +defenderseDe(Ejercito)
}
Class Ejercito{
    +atacar(País)
    +batallarCon(Ejercito)
    +reducir(Tamanio)
}
Class Objetivo{
    +verificarSiGane(PaisesOcupados): Boolean
    -verificarQueTengaMitadDePaises(PaisesOcupados): Boolean
}
Class ObjetivoOcupar{
    +verificarSiGane(DePaisesOcupados): Boolean
    -paisesDelObjetivoEstanEn(PaisesOcupados): Boolean
}
Class ObjetivoDestruir{
    -jugadorADestruir:Jugador
    +verificarSiGane(PaisesOcupados): Boolean
    -verificarQueJugadorFueDestruido(): Boolean
}
Class GestorDeCanje{
    +validarCanje(TresTarjetas): Boolean
    +dameCantidadDeEjercitos(numeroDeCanje, TarjetasUsadas): Integer
    -verificarQueCanjeEsValido(TresTarjetas): Boolean
}
Class CampoDeBatalla{
    +iniciarBatalla(ejercitoAtacante, ejercitoDefensor)
    +comparar()
}


Juego *-down- Jugador
Juego -- Tarjeta
Continente *-down- País
País o-up- Ejercito
Jugador *-left- País
CampoDeBatalla -Down- Dado
Jugador -- Ejercito
Jugador -down- Objetivo
Jugador -right- Tarjeta
Jugador *-down- GestorDeCanje
Tarjeta .down. GestorDeCanje 
Objetivo <|-down- ObjetivoOcupar
Objetivo <|-down- ObjetivoDestruir
Ejercito ..> CampoDeBatalla


@enduml
