@startuml SecuenciaObjetivos
title Jugador realiza canje exitosamente
skinparam style strictuml
actor Jugador
participant PrimerCanje

Jugador -> PrimerCanje: realizarCanje(Tarjeta1, Tarjeta2, Tarjeta3)
group compara tarjetas
PrimerCanje -> PrimerCanje: compararTarjetas()
note right
en caso de tarjetas correctas: canjeRealizado = true
end note
end

Jugador <-- PrimerCanje: 4


Jugador -> PrimerCanje: actualizarCanje()
create SegundoCanje
PrimerCanje -> SegundoCanje: <create>
Jugador <-- PrimerCanje: SegundoCanje

@enduml