@startuml Diagrama de secuencia - hay clases presenciales
title Argentina ataca a brasil y lo ocupa
skinparam style strictuml
actor Jugador1 as JugadorAtacante
participant "argentina:Pais" as PaisAtacante
participant "ejercitoArgentino:Pais" as EjercitoAtacante
participant "brasil:Pais" as PaisAtacado
participant "ejercitoBrasileño:Pais" as EjercitoAtacado
' participant "unTablero:Tablero" as Tablero
participant "unosDados:Dados" as Dados

actor Jugador2 as JugadorAtacado


JugadorAtacante -> JugadorAtacante: VerificarAtaqueValido("brasil")
JugadorAtacante -> PaisAtacante: atacar("brasil")
PaisAtacante -> PaisAtacante: esLimitrofe("brasil")
' PaisAtacante -> PaisAtacado: serAtacado()
PaisAtacante -> EjercitoAtacante: atacar("brasil")
EjercitoAtacante -> Dados: ataco(self.tamanio)
EjercitoAtacante <-- Dados: [6,4,1]
EjercitoAtacante -> PaisAtacado: serAtacadoCon([6,4,1])
PaisAtacado -> EjercitoAtacado: defenderseDe([6,4,1])
EjercitoAtacado -> Dados: defenderme(self.tamanio)
EjercitoAtacado <-- Dados: [5]









' --------------------------------------------------
EjercitoAtacado --> PaisAtacado: derrotado
PaisAtacado -> JugadorAtacado: desocupar()
PaisAtacado --> JugadorAtacante: puedeOcupar
JugadorAtacante -> PaisAtacado: ocupar()


@enduml