@startuml Diagrama de secuencia - hay clases presenciales
title Ronda de colocacion de paises
skinparam style strictuml

participant Juego
actor Jugador1 as JugadorAzul
participant PaisAzul
participant ejercitoAzul
participant Continente
participant TarjetaPais

Juego -> JugadorAzul: rondaDeColocacionPaises()
loop cantidad de paises ocupados / 2
	JugadorAzul -> PaisAzul: incrementarEjercito(5)
	PaisAzul -> ejercitoAzul: incrementar(5)
end 

Juego -> JugadorAzul: rondaDeColocacionContinentes()
loop para cada continente
    JugadorAzul -> Continente: ejercitoPorContinente(Paises)
    return cantidadEjercitos
end
loop cantidadEjercitos
	JugadorAzul -> PaisAzul: incrementarEjercito(cantidadEjercitos)
	PaisAzul -> ejercitoAzul: incrementar(cantidadEjercitos)
end

Juego -> JugadorAzul: activarCartas()
JugadorAzul -> TarjetaPais: activar(paises)


@enduml